config/routes.rb
Rails.application.routes.draw do
  resources :artists, only: [:index, :show]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :artist
  has_many :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :albums
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :album
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end

  def show
    @artist = Artist.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>

<% @artists.each do |artist| %>
  <div>
    <img src="<%= artist.image_url %>" alt="<%= artist.name %>" width="500" height="300">
    <h3><%= artist.name %></h3>
    <%= link_to "Ver más", artist_path(artist) %>
  </div>
<% end %>

app/views/artists/show.html.erb
<h3><%= @artist.name %> Albums</h3>
<div>
  <% @artist.albums.each do |album| %>
    <article>
      <h4><%= album.name %></h4>
      <img src="<%= album.image_url %>" alt="<%= album.name %>" width="250" height="180">
      <p>Released_at: <%= album.released_at %></p>
    </article>
  <% end %>
</div>
<div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musica</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>